options:
  overlay:
    type: string
    default: 250.0.0.0/8
    description: The overlay network cidr.
  underlay:
    type: string
    default: 10.0.0.0/16
    description: the underlay network cidr.
